display_name: PuNote
publisher_display_name: PuNote
identity_name: PuNote
msix_version: 2.3.1.0
logo_path: windows\runner\resources\app_icon.ico
capabilities: internetClient, internetClientServer, privateNetworkClientServer
languages: en-us,zh-cn
protocol_activation: PuNote
execution_alias: PuNote
sign_msiz: "false"
# certificate_path: windows\sign.pfx
# certificate_password:
publisher: CN=8CB43675-F44B-4AA5-9372-E8727781BDCC
install_certificate: "false"
enable_at_startup: "true"
startup_task:
  parameters: --autostart
