display_name: PuNote
package_name: PuNote
generic_name: PuNote
# maintainer:
#   name: PuNote
#   email: linux@PuNote.com

icon: ./assets/icon/icon-120.png

categories:
  - Tool

keywords:
  - PuNote
  - markdown
  - note
  - encryption

priority: optional
section: x11
installed_size: 6604
essential: false

postinstall_scripts:
  - echo "Installed PuNote"
postuninstall_scripts:
  - echo "Surprised Why?"

startup_notify: true
